[project]
name = "hellovr-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vivek", email = "vivekrajraghav@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "pydantic[email]>=2.13.5",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
hellovr-ai = "hellovr_ai:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
